config/routes.rb
Rails.application.routes.draw do
  
  get '/contact', to: 'contact#new'
  post '/contact', to: 'contact#index'
  get '/contact/new', to: 'contact#new'
  post '/contact', to: 'contact#create'

  root to: redirect('/books')

  resources :books, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

# Defines what a book is and fetches data from the API
class Book
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  include HTTParty
  attr_accessor :id, :title, :isbn, :coverUrl, :description

  def initialize(attributes = {})
      attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

  # INDEX
  def self.all
    info = get('/books')
    return unless info.success?

    info = info.parsed_response
    books = []
    info['data'].each do |b|
      books << Book.new(b)
    end
    books
  end

  # SHOW
  def self.find(id)
    info = get("/books/#{id}")
    return unless info.success?

    info = info.parsed_response
    Book.new(info['data'])
  end

  def self.search(title)
    info = get("/books?title=#{title}")
    return unless info.success?

    info = info.parsed_response
    books = []
    info['data'].each do |b|
      books << Book.new(b)
    end
    books
  end

  base_uri 'http://localhost:8080'
  headers 'Accept' => 'application/json'
  headers 'Content-Type' => 'application/json'
  format :json
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# frozen_string_literal: true

# BooksController allows users to list and view single books
class BooksController < ApplicationController
# GET /books
def index
  if params[:title].present?
    @books = Book.search(params[:title])
  else
    @books = Book.all
  end
end

def show
  @book = Book.find(params[:id])
end

def contact_us; end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
  end

  def index
    @email = params[:email]
    @message = params[:message]
    
  end

  def create        
    redirect_to contact_path(email: params[:email], message: params[:message])
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<div class="row my-2">
  <div class="col">
    <form class="form-inline" action="<%= books_path %>" method="get">
      <div class="form-group mb-2">
        <label for="book-title" class="sr-only">Book title</label>
        <input type="text" name="title" class="form-control" id="book-title" placeholder="Book title">
      </div>
      <button type="submit" class="btn btn-primary mb-2">Search</button>
    </form>
  </div>
</div>


<table class="table">
  <thead>
    <tr>
      <th scope="col" style="width: 25%;" class="text-center">Cover</th>
      <th scope="col" style="width: 75%;">Title</th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <th scope="row" class="text-center">
        <a href="<%= book_path(book.id) %>">
          <img src="<%= book.coverUrl %>" class="cover img-thumbnail shadow-sm" >
        </a>
      </th>
      <td class="align-middle">
        <a href="<%= book_path(book.id) %>">
          <%= book.title %>
        </a>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<h1 class="text-center"><strong><%= @book.title %></strong></h1>

<div class="info-area">
  <img class="img-left" src="<%= @book.coverUrl %>"/>
  <p class="text-justify"><%= @book.description %></p>
  <p class="mt-3 isbn"><strong>ISBN:</strong> <%= @book.isbn %></p>
</div>

<%= link_to 'Back', :back, class: 'mt-3 btn btn-secondary' %>

app/views/contact/index.html.erb
<div class="card border-secondary rounded-0">
  <div class="card-body p-3">
    <p>Hello!</p>
    <p>Just to let you know that we recieved your contact from : <%= @email %> </p>
    <p> with the following message: </p>
    <p> <%= @message %></p>
    <p>We will return ASAP! thanks for the contact</p>
    <div class="text-center">
      <%= link_to 'Home', books_path, class: 'btn btn-info btn-block rounded-0 py-2' %>
    </div>
  </div>  
</div>

app/views/contact/new.html.erb
<form class="mt-3" action="<%= contact_path %>" method="post">
  <div class="card border-success rounded-0">
    <div class="card-header p-0">
      <div class="bg-success text-white text-center py-2">
        <h3><i class="fa fa-envelope"></i> Contact us</h3>
        <p class="m-0">We apreciate it!</p>
      </div>
    </div>
    <div class="card-body p-3">
      <div class="form-group">
        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <div class="input-group-text"><i class="fa fa-envelope text-info"></i></div>
          </div>
          <input type="email" class="form-control" id="email" name="email" placeholder="sample@gmail.com" required>
        </div>
      </div>
      <div class="form-group">
        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <div class="input-group-text"><i class="fa fa-comment text-info"></i></div>
          </div>
          <textarea name="message" class="form-control" placeholder="Your Message" required></textarea>
        </div>
      </div>
      <div class="text-center">
        <input type="submit" value="Send" class="btn btn-info btn-block rounded-0 py-2">
      </div>
    </div>
  </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title>Books Books Books!</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column" style="min-height: 100vh;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">Books Books Books!</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="<%= books_path %>">
                Books
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= contact_new_path %>">
                Contact
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="d-flex flex-grow-1">
      <div class="container mt-1">

        <%= yield %>

      </div>
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright © Advicefront 2020</p>
      </div>
      <!-- /.container -->
    </footer>

  </body>
</html>